# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :lint do
  swiftlint(raise_if_swiftlint_error: true)
end

lane :build do |lane|
  if !lane[:configuration]
    raise "No configuration specified!".red
  end

  sh("xcodebuild -scheme OutrackWatchApp -project ../Outrack.xcodeproj -configuration #{lane[:configuration]} -destination 'platform=watchOS Simulator,name=Apple Watch Ultra (49mm)'")
end
