name: push-commit-workflow
on: push

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane lint
  
  build_in_debug:
    runs-on: macos-latest
    needs: "lint"
    steps:
      - uses: actions/checkout@v2
      - run: fastlane build configuration:"Debug"